package io.github.amarcinkowski.fastxpathaccess;

import java.nio.file.Path;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'amarcinkowski' at '22.10.16 16:31' with Gradle 2.10
 *
 * @author amarcinkowski, @date 22.10.16 16:31
 */
public class Library {
	public static String someLibraryMethod(Path path, String xpath) {
		return "";
	}

}
