package io.github.amarcinkowski.fastxpathaccess;

import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathFactory;

import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.InputSource;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'amarcinkowski' at '22.10.16 16:31' with Gradle 2.10
 *
 * @author amarcinkowski, @date 22.10.16 16:31
 */
public class Library {

	public static String[] someLibraryMethod(Path path, String xpathString) throws IOException {
		String xml = new String(Files.readAllBytes(path), "UTF-8");
		List<String> attributeValues = new ArrayList<>();
		XPathFactory xpathFactory = XPathFactory.newInstance();
		XPath xpath = xpathFactory.newXPath();
		InputSource source = new InputSource(new StringReader(xml));
		try {
			NodeList nodes = (NodeList) xpath.evaluate(xpathString, source, XPathConstants.NODESET);
			for (int i = 0; i < nodes.getLength(); i++) {
				Node node = nodes.item(i);
				attributeValues.add(node.getTextContent());
			}
			return attributeValues.toArray(new String[] {});
		} catch (Exception e1) {
			e1.printStackTrace();
		}
		return attributeValues.toArray(new String[] {});
	}

}
