package io.github.amarcinkowski.fastxpathaccess;

import static org.junit.Assert.*;

import java.nio.file.Paths;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'amarcinkowski' at '22.10.16 16:31' with Gradle 2.10
 *
 * @author amarcinkowski, @date 22.10.16 16:31
 */
public class LibraryTest {

	private final static String TEST_XML = "src/test/resources/bookstore.xml";
	private final static String XPATH_AUTOR = "/bookstore/book[1]/author";

	@Test
	public void testSomeLibraryMethod() {
		assertEquals("Giada De Laurentiis", Library.someLibraryMethod(Paths.get(TEST_XML), XPATH_AUTOR));
	}
}
